accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login' ),
    path('logout/', views.logout_view, name='logout')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('accounts.urls') )
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.todo_list, name='home' ),
    path('create/', views.todo_create, name='create'),
    path('created/', views.todo_created ),
    path('<int:id>/delete/', views.todo_delete, name='delete'),
    path('<int:id>/update', views.todo_update, name='update'),
    path('todo_updated/', views.todo_updated)
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    name = models.CharField(max_length=100)
    due_date = models.DateField()

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['name', 'due_date']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('todo:home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('todo:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('todo:home')

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Todo
from .forms import TodoForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def todo_list(request):
    Todos = Todo.objects.all()
    context = {
        'todos': Todos
    }

    return render(request, 'todo/todo_list.html', context)

@login_required(login_url='accounts:login')
def todo_create(request):
    form = TodoForm()
    context = {
        'form': form
    }
    if request.method  == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect('/created')

    return render(request, 'todo/todo_create.html', context)

def todo_created(request):
    return render(request, 'todo/todo_created.html')


def todo_delete(request, id):
    todo = Todo.objects.get(id=id)
    todo.delete()
    return render(request, 'todo/todo_deleted.html' )

def todo_update(request, id):
    todo = Todo.objects.get(id=id)
    form = TodoForm(request.POST or None, instance=todo)
    if form.is_valid():
        form.save()
        return redirect('/todo_updated')
    context = {'form': form}
    return render(request, 'todo/todo_update.html', context)


def todo_updated(request):
    return render(request, 'todo/todo_updated.html')

accounts/templates/accounts/login.html
<!-- @format -->

{% extends "base.html" %} {% block content%}
<h1>LogIn</h1>

<form action="" method="post">
  {% csrf_token %} {{form}} <input type="submit" value="Submit" />
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %} {% block content%}
<h1>Sign Up</h1>

<form action="" method="post">
  {% csrf_token %} {{form}} <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/base.html
<!-- @format -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" />
  </head>
  <body>
    <div>{% block content %} {% endblock %}</div>
  </body>
</html>

todo/templates/todo/todo_create.html
<!-- @format -->

{% extends "base.html" %} {% block content%}
<h1>Todo Create</h1>
<form action="" method="post">
  {% csrf_token %} {{form}} <input type="submit" value="Submit" />
</form>

{% endblock %}

todo/templates/todo/todo_created.html
<!-- @format -->

{% extends "base.html" %} {% block content%}
<h1>Todo Created Successfully</h1>

<a href="{% url 'todo:home' %}">Go Home</a>

{% endblock %}

todo/templates/todo/todo_deleted.html
<!-- @format -->

{% extends "base.html" %} {% block content%}
<h1>Todo Deleted Succesfully</h1>

<a href="{% url 'todo:home' %}">Go Home</a>

{% endblock %}

todo/templates/todo/todo_list.html
<!-- @format -->

{% extends "base.html" %} {% block content%} 
{% if user.is_authenticated %}

<p>Hello {{request.user.username}}! Welcome</p>
<a href="{% url 'accounts:logout' %}">Logout</a>

{% else %}

<a href="{% url 'accounts:login' %}">Login</a>
<a href="{% url 'accounts:signup' %}">Signup</a>

{% endif %}

<h1>Todo List</h1>

{% if todos %} {% for eachTodo in todos %}
<p>{{eachTodo.name}} is due on {{eachTodo.due_date}}</p>

{% if user.is_authenticated %}
<a href="{% url 'todo:delete' eachTodo.id %}"><button>Delete</button></a>
<a href="{% url 'todo:update' eachTodo.id %}"><button>Edit</button></a>

{% endif %} 

{% endfor %} {% else %}
<p>No Todo Available!</p>
<a href="{% url 'todo:create' %}">Create new Todo</a>
{% endif %} {% endblock %}

todo/templates/todo/todo_update.html
{% extends "base.html" %} {% block content%}
<h1>Todo Update</h1>
<form action="" method="post">
  {% csrf_token %} {{form}} <input type="submit" value="Submit" />
</form>

{% endblock %}

todo/templates/todo/todo_updated.html
<!-- @format -->

{% extends "base.html" %} {% block content%}
<h1>Todo Updated</h1>

<a href="{% url 'todo:home' %}">Go Home</a>

{% endblock %}